apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-vault-tls
  namespace: vault
spec:
  secretName: internal-vault-tls
  subject:
    organizations:
    - open-cluster-management.io
    - red-chesterfield.com
  usages:
    - server auth
    - client auth
  dnsNames:
    - vault
    - vault.vault.svc
    - vault.vault.svc.cluster.local
    - vault-0.vault-internal
    - vault-1.vault-internal
    - vault-2.vault-internal
    - vault-0.vault-internal.vault.svc.cluster.local
    - vault-1.vault-internal.vault.svc.cluster.local
    - vault-2.vault-internal.vault.svc.cluster.local
  duration: 720h0m0s
  renewBefore: 168h0m0s
  privateKey:
    algorithm: "RSA"
    size: 2048
  issuerRef:
    name: ssi
    kind: ClusterIssuer