apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
    cicd.red-chesterfield.com/name: vault
    cicd.red-chesterfield.com/component: vault-operator
    cicd.red-chesterfield.com/layer: security

commonAnnotations:
    cicd.red-chesterfield.com/managed-by: gitops
    cicd.red-chesterfield.com/scm-url: git@github.com:ocm-sop/vault-operator.git

generatorOptions:
  disableNameSuffixHash: true

# configMapGenerator:
# - name: vault-plugin-secrets-github
#   files:
#   - https://github.com/martinbaillie/vault-plugin-secrets-github/releases/download/v1.1.0/vault-plugin-secrets-github-linux-amd64

helmChartInflationGenerator:
- chartName: vault
  chartRepoUrl: https://helm.releases.hashicorp.com
  chartVersion: v0.10.0
  releaseName: vault
  releaseNamespace: vault
  values: overrides.yaml


resources:
- namespace.yaml
- internal-tls-secret.yaml
- internal-tls.yaml
- public-tls-secret.yaml
- public-tls.yaml
- rbac.yaml
- aws-kms-secret.yaml
- ingress.yaml 
