apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true

helmChartInflationGenerator:
- chartName: vault
  chartRepoUrl: https://helm.releases.hashicorp.com
  chartVersion: v0.10.0
  releaseName: vault
  releaseNamespace: vault
  values: overrides.yaml


resources:
- rbac.yaml
- aws-kms-secret.yaml
- ingress.yaml 
