apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: public-vault-tls
  namespace: vault
  labels:
    use-dns01-solver: "true"
spec:
  secretName: vault-tls
  subject:
    organizations:
    - open-cluster-management.io
    - red-chesterfield.com
  usages:
    - server auth
  dnsNames:
    - vault.apps.openshift-cluster-name.base-domain.tld
  duration: 720h0m0s
  renewBefore: 168h0m0s
  privateKey:
    algorithm: "RSA"
    size: 2048
  issuerRef:
    name: psi
    kind: ClusterIssuer