apiVersion: dex.betssongroup.com/v1
kind: Client
metadata:
  name: vault-sso
  namespace: sso
spec:
  name: vault-sso
  secret: vault-sso-secret
  public: false
  redirectURIs:
    - "https://vault.apps./ui/vault/auth/oidc/oidc/callback"
    - "http://localhost:8250/oidc/callback"
    - "http://127.0.0.1:8250/oidc/callback"
  trustedPeers:
    - ocp-host-cluster